# Generated by Django 5.0.4 on 2024-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=255)),
                ('no_telp', models.CharField(max_length=12)),
                ('waktu_Buka', models.TimeField()),
                ('Waktu_Tutup', models.TimeField()),
            ],
        ),
    ]
