# Generated by Django 5.0.4 on 2024-05-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_waktu_tutup_restorant_waktu_tutup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restorant',
            old_name='waktu_Buka',
            new_name='waktu_buka',
        ),
        migrations.AddField(
            model_name='meja',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
