# Generated by Django 5.0.4 on 2024-05-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_waktu_buka_restorant_waktu_buka_meja_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meja',
            name='url',
        ),
        migrations.AddField(
            model_name='meja',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='meja',
            name='restorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_meja', to='api.restorant'),
        ),
    ]
