# Generated by Django 5.0.4 on 2024-05-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_meja_url_meja_qr_code_alter_meja_restorant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
