# Generated by Django 5.0.4 on 2024-05-03 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_menu_id_alter_menu_restorant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penggunakhusus',
            name='nama',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='penggunakhusus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ulasan',
            name='pengguna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.penggunakhusus'),
        ),
    ]
