# Generated by Django 5.0.4 on 2024-05-03 15:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_penggunakhusus_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='meja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservasi', to='api.meja'),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservasi', to='api.penggunakhusus'),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='restorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservasi', to='api.restorant'),
        ),
        migrations.AlterField(
            model_name='ulasan',
            name='pengguna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ulasan', to='api.penggunakhusus'),
        ),
        migrations.AlterField(
            model_name='ulasan',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='ulasan',
            name='restorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan', to='api.restorant'),
        ),
        migrations.CreateModel(
            name='TransaksiPembayaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(100000000)])),
                ('metode_pembayaran', models.CharField(max_length=100)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('berhasil', models.BooleanField(default=False)),
                ('reservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='api.reservasi')),
            ],
        ),
    ]
